import { useState } from 'react'
import { Bell, BookOpen, Check, ChevronDown, CircleDot, Code2, FileCode2, Folder, GitBranch, GitCommitHorizontal, GitPullRequest, Layers3, LayoutDashboard, Menu, Plus, Search, Settings2, Sparkles, Star, X, Zap } from 'lucide-react'
import './App.css'

const repos = [
  { name: 'AIVCS-core', description: 'AI-native version control system', language: 'Python', color: '#3572a5', stars: 24, forks: 5, updated: 'Updated 2h ago' },
  { name: 'AIVCS-web', description: 'AIVCS developer platform', language: 'JavaScript', color: '#f1e05a', stars: 18, forks: 3, updated: 'Updated yesterday' },
  { name: 'image-forensic-ai', description: 'AI image authenticity detection', language: 'Python', color: '#3572a5', stars: 12, forks: 2, updated: 'Updated 3d ago' },
]

function App() {
  const [view, setView] = useState('overview')
  const [modal, setModal] = useState(null)
  const [mobileOpen, setMobileOpen] = useState(false)
  const navItems = [['overview', 'Overview', LayoutDashboard], ['repository', 'Repositories', Code2], ['ai-history', 'AI History', Sparkles], ['issues', 'Issues', CircleDot, 12], ['pulls', 'Pull requests', GitPullRequest, 4]]
  const openView = (next) => { setView(next); setMobileOpen(false) }
  return <div className="app-shell">
    <header className="topbar"><button className="mobile-menu" onClick={() => setMobileOpen(!mobileOpen)}><Menu size={19} /></button><button className="brand" onClick={() => openView('overview')}><span className="brand-mark"><span /><span /></span><span>AIVCS</span></button><div className="top-search"><Search size={16} /><span>Search repositories, users, commits...</span><kbd>⌘ K</kbd></div><div className="top-actions"><button className="icon-button"><Bell size={17} /><i /></button><button className="avatar" onClick={() => openView('profile')}>SR</button></div></header>
    <div className="workspace"><aside className={`sidebar ${mobileOpen ? 'sidebar-open' : ''}`}><div className="workspace-switcher"><div className="workspace-avatar">S</div><div><strong>Sumanth Rayalu</strong><small>Personal workspace</small></div><ChevronDown size={15} /></div><div className="sidebar-label">Workspace</div><nav>{navItems.map(([id, label, Icon, count]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => openView(id)}><Icon size={17} /><span>{label}</span>{count && <em>{count}</em>}</button>)}</nav><div className="sidebar-label repo-label">Your repositories <button onClick={() => setModal('repository')}><Plus size={15} /></button></div><div className="mini-repos"><button onClick={() => openView('repository')}><span className="repo-dot blue" />AIVCS-core</button><button><span className="repo-dot yellow" />AIVCS-web</button><button><span className="repo-dot teal" />image-forensic-ai</button></div><div className="sidebar-bottom"><button onClick={() => openView('settings')}><Settings2 size={17} />Settings</button><div className="ai-status"><span><Zap size={14} /></span><div><strong>AI Copilot</strong><small>Ready to assist</small></div><i /></div></div></aside>
      <main className="main-content">{view === 'overview' && <Dashboard onNew={() => setModal('repository')} onRepo={() => openView('repository')} />}{view === 'repository' && <Repository onAI={() => setModal('commit')} />}{view === 'ai-history' && <AIHistory />}{(view === 'issues' || view === 'pulls') && <ListView type={view} />}{view === 'profile' && <Profile />}{view === 'settings' && <Settings />}</main>
    </div>{modal === 'repository' && <RepositoryModal onClose={() => setModal(null)} />}{modal === 'commit' && <CommitModal onClose={() => setModal(null)} />}
  </div>
}

function PageHeader({ eyebrow, title, description, action }) { return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action}</div> }
function Button({ children, primary = false, onClick }) { return <button className={`button ${primary ? 'button-primary' : ''}`} onClick={onClick}>{children}</button> }
function PanelHeading({ title, subtitle, action }) { return <div className="panel-heading"><div><h2>{title}</h2><p>{subtitle}</p></div>{action}</div> }
function Metric({ icon: Icon, tone, label, value, note }) { return <div className="metric"><span className={`metric-icon ${tone}`}><Icon size={17} /></span><small>{label}</small><strong>{value}</strong><em>{note}</em></div> }
function Dashboard({ onNew, onRepo }) { return <><PageHeader eyebrow="Tuesday, September 22, 2026" title="Good morning, Sumanth" description="Here's what's happening across your workspace." action={<Button primary onClick={onNew}><Plus size={16} />New repository</Button>} /><section className="metrics"><Metric icon={GitCommitHorizontal} tone="purple" label="Commits this week" value="38" note="↑ 12% from last week" /><Metric icon={GitPullRequest} tone="blue" label="Open pull requests" value="4" note="2 need your review" /><Metric icon={Sparkles} tone="amber" label="AI insights generated" value="126" note="↑ 24% from last week" /></section><div className="content-grid"><section className="panel repo-panel"><PanelHeading title="Your repositories" subtitle="Active projects in your workspace" action={<button className="text-button" onClick={onRepo}>View all <span>→</span></button>} /><div className="repo-cards">{repos.map(repo => <button className="repo-card" key={repo.name} onClick={onRepo}><div className="repo-card-top"><span className={`repo-dot ${repo.language === 'Python' ? 'blue' : 'yellow'}`} /><strong>{repo.name}</strong><span className="private-badge">Public</span></div><p>{repo.description}</p><div className="repo-card-meta"><span><i style={{ background: repo.color }} />{repo.language}</span><span><Star size={13} />{repo.stars}</span><span><GitBranch size={13} />{repo.forks}</span></div><small>{repo.updated}</small></button>)}</div></section><ActivityPanel /></div><ActivityChart /></> }
function ActivityPanel() { return <section className="panel activity-panel"><PanelHeading title="Recent activity" subtitle="Latest updates from your workspace" action={<button className="more-button">•••</button>} /><div className="activity-list"><ActivityItem icon={GitCommitHorizontal} title="Sumanth pushed to" detail="AIVCS-core" time="2h ago" color="purple" /><ActivityItem icon={GitBranch} title="Sumanth created" detail="AIVCS-web" time="Yesterday" color="blue" /><ActivityItem icon={Sparkles} title="AI generated a commit" detail="feat(auth): add JWT authentication" time="2d ago" color="amber" /><ActivityItem icon={GitPullRequest} title="Pull request opened in" detail="AIVCS-core #18" time="3d ago" color="green" /></div></section> }
function ActivityItem({ icon: Icon, title, detail, time, color }) { return <div className="activity-item"><span className={`activity-icon ${color}`}><Icon size={15} /></span><div><p>{title} <strong>{detail}</strong></p><small>{time}</small></div></div> }
function ActivityChart() { return <section className="panel activity-chart"><PanelHeading title="Contribution activity" subtitle="Your coding activity over the last year" action={<button className="select-button">Last 12 months <ChevronDown size={14} /></button>} /><div className="chart"><div className="chart-y"><span>40</span><span>30</span><span>20</span><span>10</span><span>0</span></div><div className="chart-area"><div className="grid-lines" /><svg viewBox="0 0 800 155" preserveAspectRatio="none"><path d="M0 135 C40 132 55 110 90 118 S145 98 178 108 S220 77 260 88 S310 80 342 100 S388 55 428 76 S475 65 512 82 S560 45 600 65 S650 60 688 72 S740 25 800 40" fill="none" stroke="#8b78f6" strokeWidth="2.5" /><path d="M0 135 C40 132 55 110 90 118 S145 98 178 108 S220 77 260 88 S310 80 342 100 S388 55 428 76 S475 65 512 82 S560 45 600 65 S650 60 688 72 S740 25 800 40 V155 H0Z" fill="url(#fade)" opacity=".35" /><defs><linearGradient id="fade" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#8173e8" /><stop offset="1" stopColor="#8173e8" stopOpacity="0" /></linearGradient></defs></svg><div className="chart-months"><span>Oct</span><span>Dec</span><span>Feb</span><span>Apr</span><span>Jun</span><span>Aug</span><span>Sep</span></div></div></div></section> }
function Repository({ onAI }) { const files = [['src/', 'feat: organize source code', '2h', Folder], ['tests/', 'test: add auth tests', '3h', Folder], ['README.md', 'docs: update README', '5h', FileCode2], ['app.py', 'feat(auth): add JWT', '2h', FileCode2], ['requirements.txt', 'chore: update dependencies', '1d', FileCode2]]; return <><div className="repo-header"><div className="repo-title-line"><span className="repo-dot blue" /><h1>Sumanth / <strong>AIVCS-core</strong></h1><span className="visibility">Public</span></div><p>AI-native version control system</p><div className="repo-stats"><Button><Star size={15} />Star <span className="button-count">24</span></Button><Button><GitBranch size={15} />Fork <span className="button-count">5</span></Button></div></div><div className="tabs"><button className="selected"><Code2 size={16} />Code</button><button><CircleDot size={16} />Issues <span>12</span></button><button><GitPullRequest size={16} />Pull Requests <span>4</span></button><button onClick={onAI}><Sparkles size={16} />AI History</button><button><Settings2 size={16} />Settings</button></div><div className="repo-toolbar"><button className="select-button"><GitBranch size={15} />main <ChevronDown size={14} /></button><div><Button><Plus size={15} />Add file <ChevronDown size={14} /></Button><Button primary onClick={onAI}><Sparkles size={15} />AI commit</Button></div></div><section className="file-explorer panel"><div className="file-breadcrumb"><Folder size={15} /> AIVCS-core <span>/</span> <strong>root</strong><span className="branch-status"><Check size={13} /> Working tree clean</span></div>{files.map(([name, commit, time, Icon]) => <button className="file-row" key={name}><Icon size={16} className={name.endsWith('/') ? 'folder-icon' : 'file-icon'} /><strong>{name}</strong><span>{commit}</span><small>{time}</small><ChevronDown size={14} className="row-arrow" /></button>)}</section><section className="readme panel"><div className="readme-header"><BookOpen size={16} />README.md <span>Preview</span></div><div className="readme-body"><h2><span>#</span> AIVCS</h2><p className="lead">AI-native version control system.</p><hr /><h3><span>#</span># Features</h3><ul><li><Sparkles size={14} />AI-generated commits</li><li><Zap size={14} />Intelligent diffs</li><li><Layers3 size={14} />Semantic history</li><li><Code2 size={14} />Developer-first workflow</li></ul><h3><span>#</span># Installation</h3><pre><code><span>$</span> git clone https://aivcs.dev/sumanth/AIVCS-core{`\n`}<span>$</span> cd AIVCS-core{`\n`}<span>$</span> pip install -r requirements.txt</code></pre></div></section></> }
function AIHistory() { return <><PageHeader eyebrow="Repository intelligence" title="AI History" description="Ask questions about your codebase and understand how it evolved." action={<div className="ai-pill"><span><Sparkles size={14} /></span>AI Copilot ready</div>} /><div className="ai-command"><div><Sparkles size={18} /><span>When was authentication changed?</span></div><kbd>⌘ ↵</kbd></div><div className="ai-layout"><section className="ai-answer panel"><div className="answer-heading"><span><Sparkles size={15} /></span><div><strong>AI Analysis</strong><small>Generated from 248 commits</small></div><span className="confidence">98% confident</span></div><h2>Authentication was significantly changed in <a>commit abc1234</a>.</h2><p>The project moved from session-based authentication to JWT authentication with access and refresh tokens. This change introduced a more scalable authentication flow for the API.</p><div className="answer-files"><small>Relevant files</small><button><FileCode2 size={14} />src/auth.py <span>+64 −12</span></button><button><FileCode2 size={14} />src/middleware.py <span>+20 −6</span></button><button><FileCode2 size={14} />tests/test_auth.py <span>+38</span></button></div></section><section className="panel questions"><PanelHeading title="Explore your history" subtitle="Suggested questions" />{['What changed in the last release?', 'Why was the API refactored?', 'Who owns the auth module?', 'Show me recent security fixes'].map((q, i) => <button key={q}><span>0{i + 1}</span>{q}<span>→</span></button>)}</section></div></> }
function ListView({ type }) { const issue = type === 'issues'; const rows = issue ? [['Authentication fails after token expiry', '#42', 'bug', 'authentication', 'opened 2 hours ago'], ['Improve repository search experience', '#41', 'enhancement', '', 'opened yesterday'], ['Add rate limiting to public API', '#39', 'security', 'api', 'opened 4 days ago'], ['Update Python dependencies', '#37', 'maintenance', '', 'opened 1 week ago']] : [['Add JWT authentication', '#18', 'feature/auth', 'main', 'updated 2 hours ago'], ['Improve API validation', '#17', 'feature/api', 'main', 'updated yesterday'], ['Refactor repository indexing', '#15', 'refactor/search', 'develop', 'updated 3 days ago'], ['Add onboarding flow', '#12', 'feature/onboarding', 'main', 'updated 1 week ago']]; return <><PageHeader eyebrow="AIVCS-core" title={issue ? 'Issues' : 'Pull requests'} description={issue ? 'Track ideas, bugs, and tasks for this repository.' : 'Review code changes and ship with confidence.'} action={<Button primary><Plus size={16} />New {issue ? 'issue' : 'pull request'}</Button>} /><div className="list-tabs"><button className="selected">Open <span>{issue ? '12' : '4'}</span></button><button>Closed <span>{issue ? '38' : '21'}</span></button><div className="list-search"><Search size={15} />Filter {issue ? 'issues' : 'pull requests'}</div></div><section className="panel rows-panel">{rows.map((row, i) => <div className="list-row" key={row[1]}><span className={`status-dot ${issue && i === 0 ? 'red' : 'green'}`}><CircleDot size={17} /></span><div><strong>{row[0]}</strong><p>{row[1]} · {issue ? <><span className={`label ${row[2]}`}>{row[2]}</span>{row[3] && <span className="label slate">{row[3]}</span>}</> : <><GitBranch size={12} />{row[2]} → {row[3]}</>}</p></div><small>{row[4]}</small></div>)}</section></> }
function Profile() { return <><div className="profile-cover" /><div className="profile-head"><div className="profile-avatar">SR</div><div><h1>Sumanth Rayalu</h1><p>@sumanth · AI Developer</p><p className="muted">Hyderabad, India · Building thoughtful tools for developers.</p></div><Button>Edit profile</Button></div><div className="profile-stats"><div><strong>42</strong><span>Repositories</span></div><div><strong>18</strong><span>Followers</span></div><div><strong>25</strong><span>Following</span></div></div><section className="panel pinned"><PanelHeading title="Pinned repositories" subtitle="Projects worth a closer look" /><div className="repo-cards">{repos.slice(0, 2).map(repo => <button className="repo-card" key={repo.name}><div className="repo-card-top"><span className="repo-dot blue" /><strong>{repo.name}</strong></div><p>{repo.description}</p><div className="repo-card-meta"><span>{repo.language}</span><span><Star size={13} />{repo.stars}</span></div></button>)}</div></section></> }
function Settings() { return <><PageHeader eyebrow="Workspace preferences" title="Settings" description="Manage your profile, workspace, and AI experience." /><div className="settings-layout"><nav className="settings-nav">{['Account', 'Profile', 'Security', 'Appearance', 'AI Settings', 'Repositories'].map((item, i) => <button className={i === 4 ? 'selected' : ''} key={item}>{item}</button>)}</nav><section className="settings-content panel"><div className="setting-section"><h2>AI Settings</h2><p>Customize how AIVCS intelligence works for you.</p></div><label>AI Provider<select><option>OpenAI</option><option>Anthropic</option></select></label><label>Model<select><option>GPT-4.1</option><option>Claude Sonnet</option></select></label><Toggle title="AI-generated commits" copy="Suggest commit messages based on your changes." /><Toggle title="Inline code explanations" copy="Show context when reviewing unfamiliar code." /><Button primary>Save changes</Button></section></div></> }
function Toggle({ title, copy }) { return <div className="setting-toggle"><div><strong>{title}</strong><p>{copy}</p></div><span className="toggle on"><i /></span></div> }
function RepositoryModal({ onClose }) { return <Modal onClose={onClose} title="Create a new repository" subtitle="A home for your code, ideas, and AI-assisted history."><label>Repository name<input value="AIVCS-project" readOnly /></label><label>Description <span className="optional">(optional)</span><input placeholder="What is this repository about?" /></label><label>Visibility<div className="radio-options"><button className="radio selected"><span />Public<small>Anyone can see this repository</small></button><button className="radio"><span />Private<small>You choose who can see this repository</small></button></div></label><div className="check-option"><span className="checkbox">✓</span><div><strong>Initialize with README</strong><small>Start with a readme file</small></div></div><Button primary onClick={onClose}>Create repository</Button></Modal> }
function CommitModal({ onClose }) { return <Modal onClose={onClose} title="AI Commit" subtitle="A clear message for the changes in your working tree."><div className="commit-progress"><div className="progress-label"><span><Sparkles size={15} />Analyzing your changes</span><strong>100%</strong></div><div className="progress-bar"><i /></div><small>3 files changed · 2.4s</small></div><div className="generated-commit"><small>AI-generated commit</small><h3>feat(auth): add JWT authentication</h3><p>Authentication was updated to use JWT with refresh-token support.</p><div><span>+84</span><span>−21</span><span>3 files</span></div></div><div className="modal-actions"><Button onClick={onClose}>Edit</Button><Button primary onClick={onClose}><Check size={15} />Use commit</Button></div></Modal> }
function Modal({ onClose, title, subtitle, children }) { return <div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={onClose}><X size={17} /></button><div className="modal-icon"><Sparkles size={19} /></div><h2>{title}</h2><p>{subtitle}</p><div className="modal-body">{children}</div></div></div> }

export default App
